import { createServerClient } from "@supabase/ssr"
import { NextResponse, type NextRequest } from "next/server"
import { withAuthCookieOptions } from "./cookie-options"

/**
 * Refresh the auth cookie on every request and gate the app routes.
 *
 * Server components cannot write cookies, so without this the session silently
 * expires mid-session and every page starts redirecting to sign-in.
 */
export async function updateSession(request: NextRequest) {
  let response = NextResponse.next({ request })

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => request.cookies.getAll(),
        setAll: (cookiesToSet) => {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value))
          response = NextResponse.next({ request })
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, withAuthCookieOptions(options)),
          )
        },
      },
    },
  )

  // getUser(), never getSession(): only the former revalidates the JWT with
  // the auth server, and a cookie is attacker-supplied input.
  const {
    data: { user },
  } = await supabase.auth.getUser()

  const path = request.nextUrl.pathname
  const isAuthRoute = path.startsWith("/signin") || path.startsWith("/signup")
  // The landing page is the one signed-out surface that is not a form. It
  // renders for everyone and swaps its own call to action when a session
  // exists, so it must not be bounced to sign-in.
  //
  // The metadata files have to be here too, and robots.txt is the one that
  // actually bit: it was answering 307 -> /signin, which means no crawler could
  // ever read the rules it contains. A robots.txt behind auth is not a strict
  // robots.txt, it is an absent one. These are generated by app/robots.ts and
  // friends, carry nothing tenant-specific, and are meaningless to protect.
  const isPublic =
    path === "/" ||
    path === "/robots.txt" ||
    path === "/sitemap.xml" ||
    path === "/manifest.webmanifest"

  if (!user && !isAuthRoute && !isPublic) {
    const url = request.nextUrl.clone()
    url.pathname = "/signin"
    // `next` is set but nothing reads it — signIn always lands on /reminders.
    // Kept because it costs nothing and is where a deep-link-preserving sign-in
    // would read from; see the note in app/actions/auth.ts.
    url.searchParams.set("next", path)
    return redirectPreservingSession(url, response)
  }

  if (user && isAuthRoute) {
    const url = request.nextUrl.clone()
    url.pathname = "/reminders"
    url.search = ""
    return redirectPreservingSession(url, response)
  }

  return response
}

/**
 * Redirect without throwing away a refreshed session.
 *
 * `getUser()` above may have rotated the auth cookie, and the library writes
 * that onto `response`. A bare `NextResponse.redirect()` is a DIFFERENT
 * response object, so those Set-Cookie headers never reach the browser: the
 * refresh is silently lost and the next request arrives with the stale token.
 * Copying them over is what makes a redirect safe to return from here.
 */
function redirectPreservingSession(url: URL, response: NextResponse): NextResponse {
  const redirect = NextResponse.redirect(url)
  for (const cookie of response.cookies.getAll()) redirect.cookies.set(cookie)
  return redirect
}
